name: "🐛 Bug Report"
description: "Submit a bug report to help us improve"
title: "[Bug]: <title>"
labels: [bug]
body:
  - type: textarea
    id: steps-to-reproduce
    validations:
      required: true
    attributes:
      label: "👟 Reproduction steps"
      description: "How do you trigger this bug? Please walk us through it step by step."
      placeholder: "..."
  - type: textarea
    id: expected-behavior
    validations:
      required: true
    attributes:
      label: "👍 Expected behavior"
      description: "What did you think would happen?"
      placeholder: "..."
  - type: textarea
    id: actual-behavior
    validations:
      required: true
    attributes:
      label: "👎 Actual Behavior"
      description: "What actually happen?"
      placeholder: "..."
  - type: input
    id: uptime-kuma-version
    attributes:
      label: "🐻 Uptime-Kuma version"
      description: "Which version of Uptime-Kuma are you running?"
      placeholder: "Ex. 1.9.x"
    validations:
      required: true
  - type: input
    id: operating-system
    attributes:
      label: "💻 Operating System"
      description: "Which OS is your server/device running on?"
      placeholder: "Ex. Ubuntu 20.04"
    validations:
      required: true
  - type: input
    id: browser-vendor
    attributes:
      label: "🌐 Browser"
      description: "Which browser are you running on?"
      placeholder: "Ex. Firefox"
    validations:
      required: true
  - type: input
    id: docker-version
    attributes:
      label: "🐋 Docker"
      description: "If running with Docker, which version are you running?"
      placeholder: "Ex. 20.10.9"
    validations:
      required: false
  - type: input
    id: docker-image-tag
    attributes:
      label: "🏷️ Docker Image Tag"
      description: "Which Docker image tag are you using? If running '1' or 'latest', please specify image hash."
      placeholder: "Ex. 1.9.1"
    validations:
      required: false
  - type: input
    id: nodejs-version
    attributes:
      label: "🟩 NodeJS Version"
      description: "If running with Node.js? which version are you running?"
      placeholder: "14.x"
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "📝 Relevant log output"
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: checkboxes
    id: no-duplicate-issues
    attributes:
      label: "👀 Have you spent some time to check if this issue has been raised before?"
      description: "Please search in the issues without filters [here](https://github.com/louislam/uptime-kuma/issues?q=)"
      options:
        - label: "I checked and didn't find similar issue"
          required: true
  - type: checkboxes
    attributes:
      label: "🛡️ Security Policy"
      description: Please review the security policy before reporting security related issues/bugs.
      options:
        - label: I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)
          required: true
